### ISSUE TITLE
🤔 UpgradeEFI2009-2010.sh only upgrades to MP41_0081_07B and not MP51_007F_03B

### ISSUE THREAD

**Issue by whimsyniche** [pigsyn/MacProFirmwareToolUpdate#9]
I flashed my firmware twice and notice that Mac 4,1 version has not changed. I watched on YouTubes and read several forums an articles; everyone's fine with their upgrade.

I am not sure what's going one.

I looked at the shell script to see what's going on.

Mac Pro 2009-2010 Firmware Tool.app/Contents/Resources/

DowngradeEFI2010-2009.sh _– downgrade to Mac Pro 5,1_ 
```
#!/bin/bash

updatesdir="/System/Library/CoreServices/Firmware Updates/MacProEFIUpdate15"
firmwaredir="/Volumes/RamDisk/MacProEFI2010-2009"
firmware="EfiUpdaterApp2.efi"
firmware2="MP51_007F_03B_LOCKED.fd"
```

UpgradeEFI2009-2010.sh _– upgrade to Mac Pro 4,1 firmware_
```
#!/bin/bash

updatesdir="/System/Library/CoreServices/Firmware Updates/MacProEFIUpdate15"
firmwaredir="/Volumes/RamDisk/MacProEFI2009-2010"
firmware="EfiUpdaterApp2.efi"
firmware2="MP41_0081_07B_LOCKED.fd"
```

I have macOS 10.11.6 with SIP Disabled. I seen the power led blink upon when holding the power button until I heard the mac boot up sound. Wait about 10 minutes and it reboots fine with my non-efi gpu. I checked System Information and still says MP41.0081.B07.

Has anyone noticed this or has your firmware upgraded as intended?

![Screen Shot 2022-07-15 at 4 45 49 PM](https://user-images.githubusercontent.com/2744219/179308206-373108cc-86b5-463e-b121-d43bbbda5e65.png)

**Comment by pigsyn** [comment]
Hello can you confirm that you are not using Encrypted HFS+ and  that SIP is disabled in Terminal ? **csrutil status**
Also, I have seen cases where you need to reselect your current Hard Drive in **System Preferences > Startup Disk**, reboot and launch Mac Pro 2009-2010 Firmware Tool.

Can I suggest that you try this alternative method below, it has been increasingly difficult to provide support.
Apple has moved .dmg files again and again over the years, on their web infrastructure, I can't provide an updated version as  my Mac Pro has 144.0.0.0.0 firmware, I can't test anything.

```
original: 'http://support.apple.com/downloads/DL1321/en_US/MacProEFIUpdate1.5.dmg'
moded with padding: 'http://support.apple.com/downloads/DL1321/en_US/MacProEFIUpdate.dmg/..'
toiday's url: https://updates.cdn-apple.com/2019/cert/041-87779-20191017-fcbc4e09-65e2-4332-83bd-9dfe7013e409/MacProEFIUpdate.dmg
```
Alternative method:
https://thehouseofmoth.com/turning-a-2009-41-mac-pro-into-a-2010-2012-51-mac-pro-2021-edition/
Old App version available here:
https://web.archive.org/web/20200205185228/http://forum.netkas.org/index.php?action=dlattach;topic=852.0;attach=645

**Comment by pigsyn** [comment]
I've reworked  the problematic url with HexFiend, could you give a try ?
[Mac Pro 2009-2010 Firmware Tool.app.zip](https://github.com/pigsyn/MacProFirmwareToolUpdate/files/9127155/Mac.Pro.2009-2010.Firmware.Tool.app.zip)

**Comment by pigsyn** [comment]
replaced from 0x1220 to 0x12AC
```
00680074 00740070 003A002F 002F0073 00750070 0070006F 00720074 002E0061 00700070 006C0065 002E0063 006F006D 002F0064 006F0077 006E006C 006F0061 00640073 002F0044 004C0031 00330032 0031002F 0065006E 005F0055 0053002F 004D0061 00630050 0072006F 00450046 00490055 00700064 00610074 0065002E 0064006D 0067002F 002E002E 00

00680074 00740070 0073003a 002f002f 00730075 00700070 006f0072 0074002e 00610070 0070006c 0065002e 0063006f 006d002f 0064006f 0077006e 006c006f 00610064 0073002f 0044004c 00310033 00320031 002f0065 006e005f 00550053 002f004d 00610063 00500072 006f0045 00460049 00550070 00640061 00740065 002e0064 006d0067 00200020 00
```

**Comment by pigsyn** [comment]
I've reworked the problematic urls with HexFiend, could you give a try ?
[Mac Pro 2009-2010 Firmware Tool 2.app.zip](https://github.com/pigsyn/MacProFirmwareToolUpdate/files/9127317/Mac.Pro.2009-2010.Firmware.Tool.2.app.zip)

**Comment by pigsyn** [comment]
@whimsyniche 
Hello, any update ?
I have updated requirements and provided a shell script if the app still doesn't work. 
Could you check test branch ?

**Comment by pigsyn** [comment]
The scripts are working as intended, I tested the downgrade process on my MacPro4,1

The important stuff happens in ExtractAndPatchEFIFiles.sh
Both 4,1 and 5,1 dmg files are needed for firmware downgrade or upgrade.

### This is what happens when upgrading:

- A ramdisk is created: /Volumes/RamDisk/

- Both dmg files are downloaded there from Apple website

- The firmware file from the MP51 dmg, 'MP51_007F_03B_LOCKED.fd', is extracted, copied and renamed 'MP41_0081_07B_LOCKED.fd' to a staging directory (/Volumes/RamDisk/MacProEFI2009-2010)

- The firmware Application 'EfiUpdaterApp2.efi', from the MP41 dmg, is extracted and copied to this staging directory

- The firmware Application is patched with EfiUpdater2009.patch.

This is to accept the renamed 'MP51_007F_03B_LOCKED.fd' crc32 signature
Some EFI identifier strings are also modified, as the program only allows MP4,1 with **older** EFI versions to be upgraded.

The firmware application expects a specific file name with a valid crc32 signature and will only execute if your MP4,1 is currently running specific EFI versions

`crc32 MP41_0081_07B_LOCKED.fd`: **76c6d7bd**
`crc32 MP51_007F_03B_LOCKED.fd`: **8b9f1d3d**

Allowed EFI versions:
MP41.88Z.0081.B04.0903051113
MP41.88Z.0081.B03.0902231259
MP41.88Z.0081.B02.0902221922
MP41.88Z.0081.B01.0902200831
MP41.88Z.0081.B00.0902051328
XS31.88Z.0081.B04.0903051113

once patched, B07 and B08 revisions are allowed to run the update:
*MP41.88Z.0081.B07.0910130729*
MP41.88Z.0081.B03.0902231259
MP41.88Z.0081.B02.0902221922
MP41.88Z.0081.B01.0902200831
*MP41.88Z.0081.B08.1001221313*
XS31.88Z.0081.B04.0903051113

And yes XS31 is the XServe !

- Then UpgradeEFI2009-2010.sh is called, copies files into /System/Library/CoreServices/Firmware Updates/, calls bless to change boot mode and firmware update is ready !

The same thing is done to prepare files for a firmware downgrade.

Also, people with B00 or B04 revisions need to upgrade their firmware before upgrading to 5,1
How to check your EFI Version: `/usr/libexec/firmwarecheckers/eficheck/eficheck --integrity-check`

### What  is needed for the firmware upgrade:

- An EFI GPU
- OS X 10.9 Mavericks and greater (tls v1.2 support for curl is mandatory)
- System Hard Drive connected to one of the native SATA ports
- SIP disabled if you are running 10.11 El Capitan or above 
- Support stops after 10.14 Mojave as 10.15 Catalina only support 64-bit apps.
- A PRAM reset before starting: Reboot and hold keys `Command + option + P + R`

**Comment by whimsyniche** [comment]
Thanks for this response. Working and interviewing for product design roles.


I forgot to mention one context before posting this issue. I tried to use a EFI GPU ATI 5770 1GB. It messed up the macOS kernel cache. Getting back to using a non-EFI GPU was a challenge and not even resetting NVRAM solved it. Thankfully, I had remote management enabled so I can see what's happening via SSH and remote desktop. Clearing the kernel cache several times did the trick so I can use the Gigabyte R9 280X v2 again without issues.

I was considering flashing the R9 280X.

I will try out your repackage zip file and I will report back.

~~I think my ambition to update to MP51 will not happen. I have no time to invest in this endeavor as much as I had done up until recent.~~

**Comment by whimsyniche** [comment]
Hi @pigsyn I decided to sell the Mac Pro 2009. I don't have time to work on this as a side project.

Thank you for you help. I tried a little but my bandwidth was maxed with other priorities. I hope you understand.
